//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 3.0.1185.0 using the following command:
// xscgen valcurs.xsd --namespace CurrencyRatesGateway.CbRFAdapter.Models
namespace CurrencyRatesGateway.CbRFAdapter.Models
{
    
    
    /// <summary>
    /// <para>Официальные курсы валют на заданную дату, устанавливаемые ежедневно</para>
    /// </summary>
    [System.ComponentModel.DescriptionAttribute("Официальные курсы валют на заданную дату, устанавливаемые ежедневно")]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ValCurs", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ValCurs", Namespace="")]
    public partial class ValCurs
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ValCursValute> _valute;
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Valute")]
        public System.Collections.ObjectModel.Collection<ValCursValute> Valute
        {
            get
            {
                return _valute;
            }
            private set
            {
                _valute = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ValCurs" /> class.</para>
        /// </summary>
        public ValCurs()
        {
            this._valute = new System.Collections.ObjectModel.Collection<ValCursValute>();
        }
        
        /// <summary>
        /// <para>Дата установления курса (может отличатся от запрашиваемой если на запрашиваемою дату курс не устанавливался)</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute(("Дата установления курса (может отличатся от запрашиваемой если на запрашиваемою д" +
            "ату курс не устанавливался)"))]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("Date")]
        public string Date { get; set; }
        
        /// <summary>
        /// <para>Имя документа</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Имя документа")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "3.0.1185.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ValCursValute", Namespace="", AnonymousType=true)]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValCursValute
    {
        
        /// <summary>
        /// <para>ISO Цифр. код валюты</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ISO Цифр. код валюты")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("NumCode")]
        public ushort NumCode { get; set; }
        
        /// <summary>
        /// <para>ISO Букв. код валюты</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("ISO Букв. код валюты")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("CharCode")]
        public string CharCode { get; set; }
        
        /// <summary>
        /// <para>номинал. ед</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("номинал. ед")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Nominal")]
        public uint Nominal { get; set; }
        
        /// <summary>
        /// <para>Название валюты</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Название валюты")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Name")]
        public string Name { get; set; }
        
        /// <summary>
        /// <para>Значение</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Значение")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("Value")]
        public string Value { get; set; }
        
        /// <summary>
        /// <para>Курс за 1 единицу валюты</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Курс за 1 единицу валюты")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("VunitRate")]
        public string VunitRate { get; set; }
        
        /// <summary>
        /// <para>Внутренний уникальный код валюты</para>
        /// </summary>
        [System.ComponentModel.DescriptionAttribute("Внутренний уникальный код валюты")]
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlAttributeAttribute("ID")]
        public string Id { get; set; }
    }
}
